### Atividade

Instruções

- Resolver as questões abaixo. Subir o notebook em um repositório público no GitHub e enviar no [Formulário](https://docs.google.com/forms/d/e/1FAIpQLSf8IUCLt4kowhHhB3SRQofE2I8NuXuDadBYjRHqUxgb3yWOaQ/viewform)
- Para os gráficos finais de cada questão, eles devem possuir título, rótulo dos eixos definidos e legenda (quando necessário).

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px


#### Questão 1

Criar 2 vetores, um com uma série historica de anos de 1970 até 2022 e um segundo vetor com a mesma quantidade de observações e números inteiros aleatórios variando de 1 a 20000. Em seguida montar um gráfico com a melhor visualização para os dados com a biblioteca Plotly Express.

In [2]:
anos = np.arange(1970, 2023)
anos

array([1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980,
       1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991,
       1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
       2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022])

In [3]:
valores = np.random.randint(1, 20001, len(anos))
valores

array([16404,  1277, 13971, 13420,  1968, 10602, 12045,    12,   574,
       14152, 18549,  9729,  6106,  8063, 18032, 17893, 17685, 17593,
        8018,  9794,  6221,  4774,  1623, 11777, 10398,  2736, 17031,
       15360,  6190, 17130,  4248,  6257, 15842,   794, 14205,   252,
        9387, 17781,  1856,  8585, 19976, 13667, 16543,  5254,  6564,
        2369,  3280,  2653, 18892,  5440,  4330, 10448, 15033])

In [27]:
fig = px.line(x=anos, 
              y=valores, 
              markers=True)

fig.update_layout(  xaxis_title="Anos",
                    yaxis_title="Números",
                    title={'text': "Números aleatórios por ano",
                            'y':0.95,
                            'x':0.5,
                            'xanchor': 'center',
                            'yanchor': 'top'})

fig.show()

#### Questão 2

Criar uma lista com as letras do alfabeto, depois um vetor com a mesma quantidade de observações e números inteiros aleatórios variando de 10 a 100. Em seguida montar um gráfico com a melhor visualização para os dados com a biblioteca Plotly Express.

Utilize o objeto string para resolver a questão:

```
import string
string.ascii_lowercase
```

In [28]:
import string

In [6]:
var = 'eu amo python'
list(var)

['e', 'u', ' ', 'a', 'm', 'o', ' ', 'p', 'y', 't', 'h', 'o', 'n']

In [31]:
letras = list(string.ascii_lowercase)

In [32]:
num = np.random.randint(10, 101, len(letras))
num

array([87, 86, 10, 35, 61, 43, 92, 93, 41, 54, 66, 46, 90, 27, 42, 40, 13,
       87, 27, 47, 72, 32, 95, 33, 17, 17])

In [43]:
fig_2 = px.bar(x=letras, 
               y=num, 
               text=num, 
               color=letras)

fig_2.update_layout(  xaxis_title="Letras",
                      yaxis_title="Quantidade de ocorrência",
                      legend_title="Letras",
                      title={'text': "Quantidade de ocorrência por letra",
                            'y':0.95,
                            'x':0.5,
                            'xanchor': 'center',
                            'yanchor': 'top'})

fig_2.show()

#### Questão 3

Criar 2 vetores com a mesma quantidade de observações, 500 registros , de números inteiros aleatórios, o primeiro variando de 1000 a 2000, o segundo variando de 5000 a 10000. Em seguida montar um gráfico com a melhor visualização para os dados com a biblioteca Plotly Express, demonstrando relação entre as variáveis.

In [53]:
arr1 = np.random.randint(1000, 2001, 500)
arr2 = np.random.randint(5000, 10001, 500)

In [60]:
fig_3 = px.scatter(x=arr1, 
                   y=arr2, 
                   trendline='ols')

fig_3.update_layout(  xaxis_title="Array 1",
                      yaxis_title="Array 2",
                      title={'text': "Gráfico de Dispersão",
                            'y':0.95,
                            'x':0.5,
                            'xanchor': 'center',
                            'yanchor': 'top'})

fig_3.show()

#### Questão 4

Criar uma vetor com 500 registros de números inteiros variando entre 125 e 857. Em seguida montar um gráfico que mostre a dispersão com a melhor visualização para os dados com a biblioteca Plotly Express.

In [61]:
vet = np.random.randint(125, 858, 500)

In [88]:
px.histogram(x=vet,
             color_discrete_sequence = ['darkorange'])

In [89]:
px.box(y=vet)