### Atividade

Instruções

- Resolver as questões abaixo. Subir o notebook em um repositório público no GitHub e enviar no [Formulário](https://docs.google.com/forms/d/e/1FAIpQLSf8IUCLt4kowhHhB3SRQofE2I8NuXuDadBYjRHqUxgb3yWOaQ/viewform)
- Para os gráficos finais de cada questão, eles devem possuir título, rótulo dos eixos definidos e legenda (quando necessário).

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px


#### Questão 1

Criar 2 vetores, um com uma série historica de anos de 1970 até 2022 e um segundo vetor com a mesma quantidade de observações e números inteiros aleatórios variando de 1 a 20000. Em seguida montar um gráfico com a melhor visualização para os dados com a biblioteca Plotly Express.

In [2]:
anos = np.arange(1970, 2023)
anos

array([1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980,
       1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991,
       1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
       2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013,
       2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022])

In [3]:
valores = np.random.randint(1, 20001, len(anos))
valores

array([ 3058,  3813, 12229, 11054,  4276,  1252,  9762, 10254,  3594,
        7050, 15469, 16199,  9214,  5110, 13979,  7915, 14155,  7870,
        1080,  8258,  9675,  6861, 15779, 13707, 12767,  7340, 17626,
       17838,  9214,  1524, 15040, 15615,  5662,   396,  4037,  7203,
       13306, 12080,   122, 15519,  4985,  5310,  3314, 18695, 17997,
       13187, 15825,  2026, 18544, 16561,  2318, 13550, 15574])

In [4]:
fig = px.line(x=anos, 
              y=valores, 
              markers=True)

fig.update_layout(  xaxis_title="Anos",
                    yaxis_title="Números",
                    title={'text': "Números aleatórios por ano",
                            'y':0.95,
                            'x':0.5,
                            'xanchor': 'center',
                            'yanchor': 'top'})

fig.show()

#### Questão 2

Criar uma lista com as letras do alfabeto, depois um vetor com a mesma quantidade de observações e números inteiros aleatórios variando de 10 a 100. Em seguida montar um gráfico com a melhor visualização para os dados com a biblioteca Plotly Express.

Utilize o objeto string para resolver a questão:

```
import string
string.ascii_lowercase
```

In [5]:
import string

In [6]:
var = 'eu amo python'
list(var)

['e', 'u', ' ', 'a', 'm', 'o', ' ', 'p', 'y', 't', 'h', 'o', 'n']

In [7]:
letras = list(string.ascii_lowercase)

In [8]:
num = np.random.randint(10, 101, len(letras))
num

array([34, 46, 21, 82, 17, 60, 42, 83, 12, 60, 60, 57, 18, 25, 43, 91, 84,
       60, 49, 82, 87, 69, 94, 51, 51, 72])

In [9]:
fig_2 = px.bar(x=letras, 
               y=num, 
               text=num, 
               color=letras)

fig_2.update_layout(  xaxis_title="Letras",
                      yaxis_title="Quantidade de ocorrência",
                      legend_title="Letras",
                      title={'text': "Quantidade de ocorrência por letra",
                            'y':0.95,
                            'x':0.5,
                            'xanchor': 'center',
                            'yanchor': 'top'})

fig_2.show()

#### Questão 3

Criar 2 vetores com a mesma quantidade de observações, 500 registros , de números inteiros aleatórios, o primeiro variando de 1000 a 2000, o segundo variando de 5000 a 10000. Em seguida montar um gráfico com a melhor visualização para os dados com a biblioteca Plotly Express, demonstrando relação entre as variáveis.

In [10]:
arr1 = np.random.randint(1000, 2001, 500)
arr2 = np.random.randint(5000, 10001, 500)

In [11]:
fig_3 = px.scatter(x=arr1, 
                   y=arr2, 
                   trendline='ols')

fig_3.update_layout(  xaxis_title="Array 1",
                      yaxis_title="Array 2",
                      title={'text': "Gráfico de Dispersão",
                            'y':0.95,
                            'x':0.5,
                            'xanchor': 'center',
                            'yanchor': 'top'})

fig_3.show()

#### Questão 4

Criar uma vetor com 500 registros de números inteiros variando entre 125 e 857. Em seguida montar um gráfico que mostre a dispersão com a melhor visualização para os dados com a biblioteca Plotly Express.

In [12]:
vet = np.random.randint(125, 858, 500)

In [13]:
px.histogram(x=vet,
             color_discrete_sequence = ['darkorange'])

In [14]:
px.box(y=vet)